### ISSUE TITLE
parse fails with line ending after <?xml version="1.0"?>

### ISSUE THREAD

**Issue by ciez** [dredozubov/sax-parser#1]
1) this xml document is parsed ok:
```
<?xml version="1.0"?><a>
content</a>
```

2) this one fails with Fail "fail handler":
```
<?xml version="1.0"?>
<a>content</a>
```

the only difference is the Unix LF line ending after ?>

**Comment by dredozubov** [comment]
Can you show me the parser you're using for this test?

**Comment by ciez** [comment]
sure. Here it is:

```
import Debug.Trace
import Data.ByteString as B
import SAX as S

parseXmlFile::FilePath -> IO()
parseXmlFile path0 = do
    fileContent1 <- B.readFile path0
    traceIO $ show $ B.length fileContent1
    testStream fileContent1

testStream::ByteString -> IO()
testStream xml0 = traceIO resultString2
   where stream1 = S.streamXml xml0::S.SaxStream
         parser1 = S.withTag "a" S.bytes::S.SaxParser ByteString
         result1 = S.parseSax parser1 stream1::Result ByteString
         resultString2 = show result1
```

**Comment by ciez** [comment]
attaching the failing .xml file

[simple.xml.gz](https://github.com/dredozubov/sax-parser/files/3336746/simple.xml.gz)

**Comment by ciez** [comment]
using xeno-0.3.5.1 package

**Comment by dredozubov** [comment]
Thanks for the report, I found the piece of code that triggers this issue and have a fix, but I'll have to figure out how to incorporate the changes in the way that will pass the other test cases.
